---
title: "Patterns of Myth, Over-promise and Hype in New Technologies: A case of Generative AI amongst Higher Education students."
authors:
  - name: Fritz Van Deventer
    affiliation: HAN University of Applied Sciences
    roles: writing
    corresponding: true
keywords: technological innovation, beliefs, generative artificial intelligence
bibliography: references.bib
csl: springer-lecture-notes-in-computer-science.csl
abstract: Technological innovation, such as Generative Artificial Intelligence (genAI), is often promoted with hyperbole and exaggeration. Misleading beliefs about its capabilities arise and are hard to decouple from the actual utility it can bring. This pattern paper aims to identify key traits of unrealistic beliefs, so students in Higher Education can make more informed decisions on how to approach technological innovations, such as genAI.
---

## Introduction

_"I think in many ways GPT-5 is already smarter than me and many other people,"_ says Sam Altman when interviewed by Die Welt [@burgardOpenAIChefSamAltman2025]. Anthromorphisation, mystification and hype currently have surrounded Artificial Intelligence since the late 1950s [@guestUncriticalAdoptionAI2025]. AI is not alone in being communicated in a "hyped" fashion, that can involve "exaggerations about the significance or certainty of research findings [@intemannUnderstandingProblemHype2022]. This has been the case for a lot of topics such as but not limited to: neuroimaging, stem cell research, nanotechnology, genomics, and artifical intelligence.

Over the last few years there has been a great wave of AI applications, or more accurately software applications bundled with generative AI (GenAI) amongst other forms of AI. GenAI uses a variety of models to generate text, images, music and even video. Online platforms like ChatGPT, but also Copilot which is now embedded in the whole Microsoft Office suite, and even plain Google Search which always comes with a generated answer on top of the page. Signified with "AI" or ✨ it is usually a form of a Large Language Model that interprets requests and gives human-like answers.

The permeation of AI in our tools and systems is coupled with this belief that if we do not participate, we might miss the boat and will not be able to keep up with the renewed productivity our AI-using colleagues and competitors will enjoy.

But what we are seeing is not new. Firstly we have seen this before with the exact same term in different guises since the 1950s: AI [@guestUncriticalAdoptionAI2025]. What we are seeing is a repetition of technology industry overpromising new techniques or technologies and packaging them as a panacea for all kinds of problems or General Purpose Tools, while also decreasing emphasis on a large variety of negative consequences that this technology also brings. For example the profound physical impact these new technologies are having on our environment [@crawford2021atlas p. 49], the security issues of models with jailbreak attempts [@perezIgnorePreviousPrompt2022, @liMultistepJailbreakingPrivacy2023, @carliniExtractingTrainingData2021]. Technologies are not neutral by nature, and do not automatically point toward "progress".

This paper puts forward a pattern that helps recognizing language and rhetoric surrounding technological innovations to deflate the hype for students in Higher Education Institutes (HEIs).

## Related work

Surrounding "hype" a lot of research has already been done concerning studying hype [@dedehayirHypeCycleModel2016], or in its problems and defining it as something other than scientific misconduct [@intemannUnderstandingProblemHype2022], also concerning the role of emotional and/or logical expectations [@shiRoleExpectationInnovation2023] and comparing different hypes and their life cycles [@vanlenteComparingTechnologicalHype2013].

Myth and technology have a long history together. Collectively we adhere to the idea that with technology and change we also converge to a better reality, to progress. @burdett2014religion states that believing in this myth is a religious act itself.

We project ideas of what a future society can look like with these new technologies which can be called _sociotechnic imaginaries_ [@jasanoffContainingAtomSociotechnical2009].

This paper seeks to find a pattern to recognize the process where mythical belief surrounding technological innovation creates myth and polarizes criticism into categories of Luddism and technophilia, while societal pressure to participate increases.

## Methodology

This research will involve two types of qualitative analysis of language (and rhetoric) used in GenAI discourse and news articles as well as language used by HEI students.

### Thematic analysis

_Thematic analysis_ will be used as @naeemStepbyStepProcessThematic2023 and @braun2021thematic describe it to find common themes and topics in personal interview with students. Thematic analysis is a more subjective approach to data, where language is central. It requires a _coding_ process that uses semantic and latent codes to categorize statements and find _themes_ and _subthemes_ of meaning in texts.

###  Critical Discourse Analysis

Through _critical discourse analyis_ (CDA) I will look at what kind of language is constructing narratives, describes relations of power and how it creates or reinforces myths [@blommaertCriticalDiscourseAnalysis2000].

CDA tries to find patterns in power dynamics and social effects in discourse. In this analysis we can take the texts further and analyze context and intertextuality to challenge social inequalities. I will focus mainly on step two: _Identify obstacles to addressing the social wrong_ of this process which consists of three stages [@fairclough2013critical]:

1. Analyse dialectical relations
2. Select texts
3. Analyse texts interdiscursively and linguistically 

## Problem

The problem with new technologies is the "hype" created around it that leads to false beliefs or "creeds", which are hard to decouple from what the technologies actually bring to the table.  

## Solution

By discovering themes and power relations in language we can describe a recurring phenomenon in different technological transformations.

```{mermaid}
graph TD
    Sci[Scientific Community] -- Discovers --> Inno((Innovations))
    Com[Tech Companies] -. Develop .-> Inno
    Inno --> Com
    Com -. Fund .-> Sci
    Inno -. Lead to .-> Products
    Com -- Develop --> Products(New Products)
    Products -- Marketed to --> Cu{Customers}
    Com -- influence --> Media
    Media -. inflates importance .-> Cu
```

## Consequences

Being able to recognize language as hyperbolic or mythical empowers students to discern truth from propaganda.

## Forces

### Solutions over needs

Instead of looking at our needs we are often distracted by technology and try to find a way to fit in our workflow [@ervinCanTechnologyFulfill1993].

### Pace of change and fear of missing out

Technological innovations happen quickly and people fall prey to innovation anxiety [@okerekeInnovationAnxietyNew]. When anxious it is harder to discern truth from fiction.

### Advertisement from companies

Industry leaders have a very real interest in hyping their own tool, model, progress or company as they have financial interests in attrracting more users and perhaps ruling out competition. Terms like inevitability of the technology combined with solutionism approaches to a wide-scala of problems are good examples of "myth"-smells [@zheng2025resisting].

## References